fail_fast: true
repos:
  - repo: https://github.com/python-poetry/poetry
    rev: "1.5.1"
    hooks:
      - id: poetry-check
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.13
    hooks:
      - id: ruff
        types: [python]
        args: [--fix]
      - id: ruff-format
        types: [python]
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v1.14.1'
      hooks:
      -   id: mypy